project_id = "qqshsywezmoxyzyytvnp"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.chat-ai]
verify_jwt = false

[functions.demo-chat]
verify_jwt = false

[functions.send-contact]
verify_jwt = false

[functions.send-prospect]
verify_jwt = false
